### ISSUE TITLE
請問繁簡字之間是如何處理的?

### ISSUE THREAD

**Issue by jarvisaoieong** [tenlee2012/elasticsearch-analysis-hao#10]
我嘗試添加繁體字到 custom_dictionary.text 詞庫中，起不到效果。
但添加簡體字進詞庫的話，則有效果，並且同時支持繁體字的分詞，請問繁簡字之間在插件中是怎樣處理的?

**Comment by jarvisaoieong** [comment]
謝謝，了解了。

**Comment by tenlee2012** [comment]
你好，已經更新了插件代碼，現在可以在自定義詞庫custom_dictionary.text中寫入繁體字了，可以下載相應的release zip包。
