### ISSUE TITLE
特定單字的搜索支持

### ISSUE THREAD

**Issue by jarvisaoieong** [tenlee2012/elasticsearch-analysis-hao#11]
您好，想問問在不開啟 enableSingleWord 的狀態下，能否通過某些方法來對特定的單字支持分詞以用于搜索? 
我嘗試了新增自定義詞庫的方法，但没有效果

例如:  `河南省政府今天發表重要講話` ，我想特定支持 "省" 字的搜索。
目前是分詞的結果會是 `河南省政府/河南省/河南/政府/今天/發表/重要講話/重要/講話`

**Comment by tenlee2012** [comment]
抱歉，不支持。必須設置`enableSingleWord=true`才可以。
PS: 所有的單字，都已經在詞庫裡面了，不用再把單字加到自定義詞庫中。
