### ISSUE TITLE
中英文混合词的分词, 例如: GPS定位系统

### ISSUE THREAD

**Issue by yren** [tenlee2012/elasticsearch-analysis-hao#12]
能否实现中英文混合词的分词，例如在字典中加入词 ”GPS定位系统“ , 目前好像不能分词 ”GPS定位系统“

**Comment by tenlee2012** [comment]
感谢，我会近期修复一下这个问题。

**Comment by tenlee2012** [comment]
可以分词中英混合词。
因为
词库建立的时候，不会对自定义词库进行归一化处理，”GPS定位系统“会存入词库。
搜索的时候会对输入的进行归一化处理，会把`GPS定位系统`，归一化为`gps定位系统`，导致和词库对不上。
临时解决方案是 自定义词典 输入小写 ”gps定位系统“，搜索”GPS定位系统“或者”gps定位系统“都会正常了。

**Comment by tenlee2012** [comment]
我会优化一下，自定义词库 不用人工做归一化后放入词库里。

**Comment by yren** [comment]
cool,  试了一下好使。  我在生成自定义词典时，可以将英文转为小写。这样临时用完全没问题。
之前试过 ik , 和 jieba (https://github.com/sing1ee/elasticsearch-jieba-plugin) 分词。你的分词器对最定义词典支持的效果最好。

**Comment by tenlee2012** [comment]
感谢认可！感谢认可！

**Comment by tenlee2012** [comment]
已经push到dev分支，可以根据自己的es版本号修改pom.xml的elasticsearch.version属性后，重新打包即可`mvn clean package -Dmaven.test.skip=true`。

**Comment by tenlee2012** [comment]
release文件已经打包好了，可以下载更新插件了。
