### ISSUE TITLE
请问  hao_search_mode/hao_index_mode 什么区别？

### ISSUE THREAD

**Issue by qbit-git** [tenlee2012/elasticsearch-analysis-hao#21]
请问 hao_search_mode/hao_index_mode 什么区别？建议 readme 里面做明确介绍。

**Comment by tenlee2012** [comment]
感谢，readme已更新。

**Comment by qbit-git** [comment]
看样子 search_mode 分词结果是 index_mode 分词结果的子集哈？
ik_smart 并不是 ik_max_word 的子集，所以确认下。
https://github.com/medcl/elasticsearch-analysis-ik/issues/584

**Comment by tenlee2012** [comment]
的确是子集。能保证建索引和搜索时候的一致性
