### ISSUE TITLE
在对短文本分词时，建议将原文本作为分词结果之一返回

### ISSUE THREAD

**Issue by qbit-git** [tenlee2012/elasticsearch-analysis-hao#27]
当前“镐窝”会被分词为两个单字，在对短文本分词时，建议将原文本作为分词结果之一返回，可通过配置项开关。
例如将“镐窝”分词为“镐窝”“镐”“窝”
这样可以一定程度缓解没有命名实体识别和新词发现的问题，对一些不常见的人名分词有帮助。

**Comment by tenlee2012** [comment]
那长文本情况下呢？还是分成了两个字，搜的时候还是搜不出来。。所以，还是得加到词库里，词库的维护是个长久的工作

**Comment by qbit-git** [comment]
我的应用场景有一点特殊，建索引的时候有很多字段本身是结构化的短文本。例如：作者、关键词。所以还是希望增加可以短文本作为分词结果之一的可配置选项。
![image](https://user-images.githubusercontent.com/61911047/146025436-54bda142-df69-4522-938c-781e2ced799e.png)
