### ISSUE TITLE
希望词典支持配置多个文件

### ISSUE THREAD

**Issue by qbit-git** [tenlee2012/elasticsearch-analysis-hao#28]
建议词典支持配置多个文件，对本地自定义词典和远程词典。
另外远程词典也是判断了 Last-Modified 和 ETag 的哈？建议在文档里面明确说明一下。

**Comment by tenlee2012** [comment]
已支持

**Comment by qbit-git** [comment]
看源码似乎只有本地自定义词典（customerDictionaryFile）支持多文件，远程词典（remoteFreqDict）还是没有支持哈？
