### ISSUE TITLE
Please be aware that your account is STOLEN and ABUSED by the very platform!

### ISSUE THREAD

**Issue by jbluv** [tenlee2012/elasticsearch-analysis-hao#5]
Hi! I'm also a user of the very platform.

I noticed that the platform admin **stole and abused your account** to make profit. Please check the two strange repo that "you" starred and forked:

![501610675252_ pic_hd](https://user-images.githubusercontent.com/76879803/104670545-02563300-5717-11eb-855a-dbaca1a6feb1.jpg)

![511610675281_ pic_hd](https://user-images.githubusercontent.com/76879803/104670548-05e9ba00-5717-11eb-9dde-3b028ec42625.jpg)

**Comment by MOGUIJOE** [comment]
I think GitStar.com.cn is stealing Personal Access Token from us!
