### ISSUE TITLE
有没有7.10.2版本的

### ISSUE THREAD

**Issue by 874808039** [tenlee2012/elasticsearch-analysis-hao#6]
有没有7.10.2版本的

**Comment by tenlee2012** [comment]
有，我打包一下，es更新太快了。在release页面下载。

**Comment by 874808039** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tenlee"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 晚上8:01
收件人: "tenlee2012/elasticsearch-analysis-hao"<elasticsearch-analysis-hao@noreply.github.com&gt;; 
抄送: "Sealone"<874808039@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tenlee2012/elasticsearch-analysis-hao] 有没有7.10.2版本的 (#6)





 
有，我打包一下，es更新太快了🤣。
 在release页面下载。

**Comment by tenlee2012** [comment]
已经打包好上传了，欢迎体验！
